# Generated by Django 4.2.8 on 2023-12-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='is_epic',
            new_name='is_mythic',
        ),
    ]
